server:
  port: 8207

spring:
  application:
    name: nacos-user-service
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
