server:
  port: 8206

spring:
  application:
    name: nacos-user-service
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848 #\u914D\u7F6Enacos\u5730\u5740

management:
  endpoints:
    web:
      exposure:
        include: '*'
