server:
  port: 8004

spring:
  application:
    name: eureka-security-server
  security: #设置登陆账号和密码
    user:
      name: admin
      password: 123456

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false