server:
  port: 9301

spring:
  application:
    name: admin-security-server
  security:
    user:
      name: admin
      password: 123
  boot:
    admin:
      discovery:
        ignored-services: ${spring.application.name} #\u4E0D\u663E\u793A\u81EA\u5DF1\u7684\u76D1\u63A7\u4FE1\u606F

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka

